11/Oct/2021 15:39:58 [WARNING] django.request: Not Found: /userapi/getlinkeduser/
11/Oct/2021 15:40:32 [WARNING] django.request: Not Found: /userapi/getlinkeduser/
11/Oct/2021 16:01:23 [WARNING] django.request: Not Found: /candidate-detail/
11/Oct/2021 16:01:52 [WARNING] django.request: Not Found: /candidate-detail/1
11/Oct/2021 16:01:59 [WARNING] django.request: Not Found: /candidate-detail/1/
11/Oct/2021 16:47:38 [ERROR] django.request: Internal Server Error: /candidate/candidate-detail/1/
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view webapp.candidate.views.CandidateDetail didn't return an HttpResponse object. It returned None instead.
11/Oct/2021 16:51:58 [ERROR] django.request: Internal Server Error: /candidate/candidate-detail/1/
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view webapp.candidate.views.CandidateDetail didn't return an HttpResponse object. It returned None instead.
11/Oct/2021 17:13:37 [ERROR] django.request: Internal Server Error: /candidate/candidate-detail/1/
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view webapp.candidate.views.CandidateDetail didn't return an HttpResponse object. It returned None instead.
11/Oct/2021 17:21:45 [ERROR] django.request: Internal Server Error: /candidate/candidate-detail/1/
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jiffy/PycharmProjects/assignment/project/webapp/candidate/views.py", line 41, in dispatch
    return super(CandidateDetail, self).dispatch(*args, **kwargs)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jiffy/PycharmProjects/assignment/project/webapp/candidate/views.py", line 86, in post
    'id': post_data.get('id', [None])[0],
AttributeError: 'NoneType' object has no attribute 'get'
11/Oct/2021 17:25:05 [WARNING] django.request: Method Not Allowed: /candidateapi/candidate/1/
11/Oct/2021 17:25:34 [ERROR] django.request: Internal Server Error: /candidate/candidate-detail/1/
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view webapp.candidate.views.CandidateDetail didn't return an HttpResponse object. It returned None instead.
11/Oct/2021 22:22:42 [WARNING] django.request: Method Not Allowed: /candidateapi/candidate/1/
11/Oct/2021 22:24:41 [ERROR] django.request: Internal Server Error: /candidate/candidate-detail/1/
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view webapp.candidate.views.CandidateDetail didn't return an HttpResponse object. It returned None instead.
11/Oct/2021 22:25:17 [ERROR] django.request: Internal Server Error: /candidateapi/candidate/1
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/candidateapi/candidate/1/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
11/Oct/2021 22:26:02 [ERROR] django.request: Internal Server Error: /candidate/candidate-detail/1/
Traceback (most recent call last):
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jiffy/PycharmProjects/assignment/project/webapp/candidate/views.py", line 41, in dispatch
    return super(CandidateDetail, self).dispatch(*args, **kwargs)
  File "/home/jiffy/PycharmProjects/asgmt_env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jiffy/PycharmProjects/assignment/project/webapp/candidate/views.py", line 110, in post
    data = json.loads(resp.content)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
11/Oct/2021 23:16:26 [WARNING] django.request: Not Found: /favicon.ico
11/Oct/2021 23:45:56 [WARNING] django.request: Not Found: /candidate/create_candidate/
